### ISSUE TITLE
Failing when installing

### ISSUE THREAD

**Issue by icaroharry** [emre/utopy#1]
I'm getting this error when running `sudo pip3.6 install utopy`. I'm using Ubuntu 17.04

``` 
Installed /tmp/pip-build-k61dr1tz/steem/.eggs/pytest_pylint-0.7.1-py3.6.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k61dr1tz/steem/setup.py", line 15, in <module>
        tests_require=package_meta.default_requirements+package_meta.dev_requirements)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'

    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k61dr1tz/steem/setup.py", line 15, in <module>
        tests_require=package_meta.default_requirements+package_meta.dev_requirements)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k61dr1tz/steem/
```

**Comment by icaroharry** [comment]
I've managed to install the missing dependencies but now I'm having an issue with the `toml` package required by Steem. 

> The 'toml==0.9.3.1' distribution was not found and is required by steem

When I try to install it from `pip` I get 
```
Requested toml==0.9.3.1 from https://pypi.python.org/packages/af/06/edd820aa8a04ba82354a841af00aa28dcde391a7759a1e34579bb33d63bf/toml-0.9.3.1.tar.gz#md5=e5d32776ced9417c4149902d56a7302f (from steem==0.18.103->utopy), but installing version 0.9.3
```
It seems that steem-python is requiring this specific version that doesn't exist

**Comment by emre** [comment]
This is because of toml messing up with its version names. I manage to install it successfully via pip though. weird.

There is a workaround [here](https://steemit.com/steemit/@crokkon/steem-blockchain-access-with-python-setting-up-steem-python-with-docker) to fix toml version mismatch. Maybe you can try that.
